### ISSUE TITLE
Do You support TFS On-Prem

### ISSUE THREAD

**Issue by Eldadc** [parasoft/parasoft-findings-vsts#1]
Do You support TFS On-Prem

**Comment by benken-parasoft** [comment]
Parasoft Findings was developed as a generic extension for both VSTS and TFS.  In particular, the extension's manifest specifies "Microsoft.VisualStudio.Services" for the [installation target](https://docs.microsoft.com/en-us/vsts/extend/develop/manifest?view=vsts#installation-targets) which _"is the most common installation target and indicates that the extension can be installed into VSTS and Team Foundation Server 2015 Update 2 and later"_.  Otherwise, if your TFS installation is not compatible for some reason, Microsoft's [TFS FAQ](https://docs.microsoft.com/en-us/vsts/marketplace/tfs-extension-faqs?view=tfs-2018#q-why-doesnt-the-extension-i-want-show-a-download-button) suggests the download button would be missing.

**Comment by Eldadc** [comment]
Thanks
How can i download extension off line to a TFS server.
Thanks

**Comment by benken-parasoft** [comment]
In case this helps you, I similarly found this in Microsoft's TFS docs:
[Install extensions for disconnected TFS](https://docs.microsoft.com/en-us/vsts/marketplace/get-tfs-extensions?view=tfs-2018#install-extensions-for-disconnected-tfs)
