### ISSUE TITLE
Running on TFS on PREM 2018

### ISSUE THREAD

**Issue by Eldadc** [parasoft/parasoft-findings-vsts#2]
I am getting error on the junit xml report , it is always 1 KB size without any content.
"Failed to read ..... report.xml-junit.xml missing Root element."
It seems the converter does not operate.
The report XML and HTML looks fine.
Any suggestions ?
Thanks

**Comment by benken-parasoft** [comment]
You would probably need to share your Parasoft report file(s), so that someone might be able to explain why the internal XSL transform is not producing what you expect.  If you don't want to share that here then please consider contacting [Parasoft Support](https://www.parasoft.com/support) for a timely resolution.   

Otherwise, without having more detail from you, I can only recommend that you check the task configuration, making sure Parasoft Findings is configured to consume the correct Parasoft XML file(s).  Having the full build output and some description about what your build job is doing and how the Parasoft tool is being invoked might also be useful.  Please also make sure your Parasoft report is one of the supported formats, SOAtest Desktop 9.x or Parasoft Analyzer 10.x (C++test, Jtest and dotTEST).

**Comment by Eldadc** [comment]
Hi,

Thanks for the detailed reply. I am generating my report by using C++Test
and dotTest.
I downloaded the jar and xunit schema.
I run the command line on a different xml report files , the report files I
run it is been process successfully by Jenkins plug-in, So I believe the
report.xml is correct. Still same issue for all report.xml files

I had a warning when I run the command line : running an xslt 10 stylesheet
with an xslt 20 processor. I changed  *<xsl:stylesheet> to 2.0* .
I got this error when running the command line agtre the change:
Static error in xsl:if/@test on line 171 column 46 of xunit.xsl
XPTY0004 : In { position() != "1" } : can not compare xs:integer xs:string
Error report during stylesheet compilation.

Any suggestions ?

Thanks

**Comment by benken-parasoft** [comment]
> I am generating my report by using C++Test and dotTest.

Can you please be more specific?  As mentioned, the VSTS extension does not support all Parasoft reports,  not all versions of all products.  The report also needs to have unit test results, not static analysis, for example.  For C++test, I know the report has to come from the analyzer, not the Desktop (Eclipse) plugin.  There are many different reasons why things might not work.  You really need to provide us with the Parasoft report that you are trying to process.

> My report files are been process successfully by Jenkins plug-in

That's good.  However, I'm asking what happens with the xunit.xsl used by the VSTS extension.  Again, having a report from you would be helpful so that someone can give you a definitive answer.  If you don't want to share that here then please consider contacting [Parasoft Support](https://www.parasoft.com/support) for a timely resolution.

> running an xslt 10 stylesheet with an xslt 20 processor

Perhaps you did not pass "-versionmsg:off".  Anyway, even if you don't do that, that's a warning, not an error.

> I changed *<xsl:stylesheet> to 2.0* . I got this error when running the command line after the change

Don't change the XSL.  :)

**Comment by Eldadc** [comment]
I am using C++test 10.3.3 , running just static analysis.
If there are no unit testing in my process , so case close I believe.
It is disappointing that there is no solution to display results on TFS.

**Comment by benken-parasoft** [comment]
> I am using C++test 10.3.3 , running just static analysis.

Parasoft Findings is used to publish Parasoft functional and unit test results.  This way, all the visibility and reporting you get for unit test results you will also get for Parasoft functional and unit test results.

> It is disappointing that there is no solution to display results on TFS.

Absolutely not true!  VSTS handles static analysis results a bit different than unit test results.  In particular, VSTS can be configured to archive static analysis reports generated by various third party static analysis tools as described here in the VSTS docs](https://docs.microsoft.com/en-us/vsts/java/standalone-tools?view=vsts).  This makes the static analysis reports available in VSTS on the build's Artifact's tab.  You can publish other kinds of artifacts, including Parasoft HTML report files, using the generic [Publish Build Artifacts](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/utility/publish-build-artifacts?view=vsts) task.  Also see [Artifacts in Team Build](https://docs.microsoft.com/en-us/vsts/pipelines/build/artifacts?view=vsts).

> Where can I put an example of a very simple XML file in order to test it

I don't think I need to see your XML file at this point.  I hope this answer makes sense.

**Comment by benken-parasoft** [comment]
I'd like to clarify my last comment.  Parasoft Findings should be enhanced to publish Parasoft static analysis results into VSTS.  How this should be done is not well defined.  For non-Parasoft tools, VSTS only lets you archive the static analysis reports, which you can view directly in VSTS from the Artifacts tab.  Without making any enhancements to Parasoft Findings, you can similarly publish the Parasoft report as an build Artifact, then click on the report from the Artifacts tab to view the results.

**Comment by benken-parasoft** [comment]
> It is very strange that there is a gap between Jenkins Parasoft finding plug-in to VSTS extension.

Yes.  Understandable.  Parasoft Findings for Jenkins is more mature and has more active development.  Aside from that, Parasoft Findings looks and works differently for different CI systems because the CI systems themselves do things differently, following different paradigms.

> Publish Artifact may display the HTML\XML file but wont give a transparent view of results and ability to navigate in results and code

Yes.  As mentioned, VSTS does not have "transparent view of results" as mentioned, except for unit test results.

> I want to give developers an immediate status on the static analyse results

Absolutely.  At a minimum, I imagine Parasoft Findings producing similar "Code Analysis Report" information on the build summary page, like you get for other static analysis tools and even have an enhanced "transparent view of results" like you request.

For product enhancements, I recommend contact your Parasoft technical account representative.

**Comment by benken-parasoft** [comment]
On this topic, I notice that Microsoft now offers a "SARIF SAST Scans Tab" extension on the DevOps Marketplace.  So, if you have a build step that can translate the Parasoft static analysis XML report to SARIF format then you could leverage this extension.  This is an alternative to using the "Publish Build Artifacts" task to simply archive the Parasoft html report.

**Comment by Eldadc** [comment]
Hi,

Thanks on the updates , I need to check if C++ static analysis supports this kind of report, "SARIF SAST" ?

Thanks
